

// Submit Comment
POST http://localhost:8080/createComment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlhdCI6MTczODkxODE0MCwiZXhwIjoxNzM4OTIxNzQwfQ.qplJAjDWz-A7CncT_kaOqFfPS2Qn01CNk51x0FGYPuA
Content-Type: application/json

{
    # "_id": "67a5b28c5e196dd4dd7b75dc",
    "blogId": "679dda35a20552c27f871676",
    "username": "dev",
    "comment": "Voilaaaa..."
}

###

POST http://localhost:8080/getCommentsOfBlog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlhdCI6MTczODkxODE0MCwiZXhwIjoxNzM4OTIxNzQwfQ.qplJAjDWz-A7CncT_kaOqFfPS2Qn01CNk51x0FGYPuA
Content-Type: application/json

{
    "blogId": "679dda35a20552c27f871676"
}


###

//Delete Commnet
POST http://localhost:8080/deleteComment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlhdCI6MTczODkxODE0MCwiZXhwIjoxNzM4OTIxNzQwfQ.qplJAjDWz-A7CncT_kaOqFfPS2Qn01CNk51x0FGYPuA
Content-Type: application/json

{
    "_id": "67a5ac8d3b7e4314c1d484aa"
}


###
// Registration Request
POST http://localhost:8080/register

{
    "username": "disco",
    "email": "disco@gmail.com",
    "password": "disco123"
    
    }
###

// Login Request - Authenticates user with username and password
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "dev",
    "password": "dev123"
}



###
// Get All Blogs Request - Retrieves all blog posts from database
POST http://localhost:8080/getallblogs
Content-Type: application/json
Authorization: Bearer ${localStorage.getItem('token')}



###
// Create Blog Request - Creates a new blog post with title and content
POST http://localhost:8080/createblog 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt1bmFsIiwiaWF0IjoxNzM4MjEyMDQ4fQ.u5xwHbt_ucJndmbEyCmv-Rk0MKcd78byVXaUBrDsaGs

{
    "title": "APaaI Te11111st",
    "content": "API Test Content"
}


###
// Get Single Blog Request - Retrieves a specific blog post by title
POST http://localhost:8080/getSingleBlog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlhdCI6MTczODkxODE0MCwiZXhwIjoxNzM4OTIxNzQwfQ.qplJAjDWz-A7CncT_kaOqFfPS2Qn01CNk51x0FGYPuA
Content-Type: application/json

{
   "_id" : "679dda35a20552c27f871676"
}

###
POST http://localhost:8080/deleteblog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt1bmFsIiwiaWF0IjoxNzM4MjEyMDQ4fQ.u5xwHbt_ucJndmbEyCmv-Rk0MKcd78byVXaUBrDsaGs

{
    "title": "hell1"
}