import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    draftsRefreshFlag: false,
}

const toggleSlice = createSlice({
    name: 'toggle',
    initialState,
    reducers: {
        setDraftsRefresh: (state) => {
            state.draftsRefreshFlag = !state.draftsRefreshFlag;
        }
    }
});

// Destructure and export the action creators that were automatically generated by createSlice
// These action creators (setBlogsRefresh, setDraftsRefresh) can be imported and dispatched 
// to trigger state changes defined in the reducers
export const { setDraftsRefresh } = toggleSlice.actions;

// Export the reducer function that was generated by createSlice
// This reducer handles all state updates for this slice and should be included in the store
export default toggleSlice.reducer;